### PR TITLE
Rolemanagement wip

### PR DESCRIPTION
**Pull request by mikeshardmind**

### CODE REVIEW

**Comment by mikeshardmind** [comment]
After fixing up a few minor issues with the basic implementation, this still needs me to decide on how I want to handle interactions with this and muted users.

My gut instinct on this is that there needs to be something exposed on the bot object for this in case other tools ever have similar concerns.

**Comment by DiscordLiz** [comment]
Other than style issues, was there anything else you needed to do for this to be review ready?

**Comment by mikeshardmind** [comment]
TooManyArguments is only raised after all parsing or arguments happens, so to have consistent handling occur here, I need to do a little more to this.

Example:

`roleset viewrole Multiword Rolename` won't prompt them to quote it unless "Multiword" is itself also the name of a role.

I'll handle this later this evening (hopefully) and once happy with it, I'll mark it as ready for review.

**Comment by mikeshardmind** [comment]
I didn't test the handling on roles here. I assume it's fine, but as I don't have time to go over it tonight, I'm not marking this as ready. If for some reason you want to test that knowing that I haven't done my end of it, if that works as intended, there's nothing else I intend to do to this change wise unless an issue is noticed @DiscordLiz

**Review by DiscordLiz — APPROVED** [review]

**Pull request merged**
